device: auto
job_name: ${model.name}_${dataset.name}_${dataset.user_group}
run_dir: outputs/${job_name}/${now:%Y-%m-%d_%H-%M-%S}
model_ckpt: null

wandb:
  enabled: false
  project: null
  entity: null
  name: ${job_name}

python_logging:
  level: INFO
