strategy: auto
accelerator: gpu
devices: 1
precision: 16-mixed
log_every_n_steps: 1
hidden_dim: 512
embedding_dim: 256
n_epochs: 1000
batch_size: 8192
lr: 1e-5
gradient_clip_val: 1.0
save_cycle: 5000
eval_after_training: False

checkpoint:
  save_last: False
  save_top_k: 0
  every_n_train_steps: null
  every_n_epochs: 500
