name: commercial
geography: null
normalize: True
scale: True
use_learned_normalizer: True
threshold: 8
seq_len: 24
time_series_dims: 1
shuffle: True
path: "./data/commercial/csv"
time_series_columns: ["energy_meter"]
data_columns: ["dataid","energy_meter","timestamp"]
metadata_columns: ["building_id", "site_id", "primaryspaceusage", "sub_primaryspaceusage", "sqm", "sqft", "yearbuilt"]
numeric_context_bins: 5
numeric_cols: ["sqm", "sqft", "yearbuilt"]  # Columns to bin as numeric

context_vars: # for each desired context variable, add the name and number of categories
  year: 5
  month: 12
  weekday: 7
  site_id: 19
  primaryspaceusage: 17
  sub_primaryspaceusage: 105
  sqm: 5
  sqft: 5
  yearbuilt: 5

